# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  app.brochure_uploader:  
        class: AppBundle\FileUploader
        arguments: ['%brochures_directory%']

  app.doctrine_brochure_listener:
          class: AppBundle\EventListener\BrochureUploadListener
          arguments: ['@app.brochure_uploader']
          tags:
              - { name: doctrine.event_listener, event: prePersist }
              - { name: doctrine.event_listener, event: preUpdate }